---
title: "Results FPP Conditioning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In the following the results of the fear profiles pilot conditioning task are presented.


``` {r include = FALSE}

rm(list = ls())

### Load packages
library(ggplot2)
library(grid)
library(gridExtra)
library(ez)
library(lsr)
library(psychReport)
library(tidyr)

options(scipen = 999)

### Functions
# SE-Function
se <- function(x) {
  sd(x, na.rm=T)/(sqrt(n))
}

```

## Skin Conductance Response

``` {r include = FALSE}

### Load data
load("scr_FPP_forR.RData")

# Exclude outliers: participants with less than 8/12 or 4/6 responses to the US 
scr_FPP_forR <- scr_FPP_forR[!((scr_FPP_forR$ID == '008') | (scr_FPP_forR$ID == '014') | (scr_FPP_forR$ID == '022') | (scr_FPP_forR$ID == '037') | (scr_FPP_forR$ID == '057')),]
#Note: 024 shows response to 5 USs, but not a single response to any CS

```


``` {r echo = FALSE}


phase <- c("acq","ext","ren")
reinf <- c("all","100","050")

for (i in phase){

  cat(paste0('Experimental Phase: ', i, '\n'))
  
  for (k in reinf){
    
    cat(paste0('Reinforcement group: ', k, '\n'))

# create data subset
if (k == "all"){
dataSubset <- scr_FPP_forR[which(scr_FPP_forR$stim != 'US' & scr_FPP_forR$phase == i),]
} else {
dataSubset <- scr_FPP_forR[which(scr_FPP_forR$stim != 'US' & scr_FPP_forR$phase == i & scr_FPP_forR$reinf_rate == k),]
}
    
# Define n for SE
n <- length(unique(dataSubset$id))
cat(paste('Sample size: n = ', n, '\n'))

agg.scr <- with(dataSubset, aggregate(log-rc, by=list(trial=trial, stim=stim, phase=phase), FUN=mean, na.rm=T))
agg.scr$se <- with(dataSubset, aggregate(log-rc, by=list(trial=trial, stim=stim), FUN=se))[ ,3]

# Timline for x-axis
if (i == "ren"){ 
agg.scr$x_axis <- c(rep(c(1:6),2))
} else {
agg.scr$x_axis <- c(rep(c(1:12),2))
}

# Order corresponding to timeline
agg.scr <- agg.scr[order(agg.scr$trial),]

# Add confidence interval
agg.scr$lower <- agg.scr$x - 1.96*agg.scr$se
agg.scr$upper <- agg.scr$x + 1.96*agg.scr$se

name_y_lab <- "SCR (microS, log, rc)" 
y_limit <- (round(max(agg.scr$upper), digits=1) + 0.1)
y_break <- 0.05  

# Plot
theme_set(theme_bw())
SCR_logrc <- ggplot(agg.scr, aes(x=x_axis, y=x, colour=stim, group=stim))+
  geom_point(aes(group=stim), size=2) +
  geom_line(aes(group=stim), size=1.2) +
  geom_ribbon(aes(ymin=lower, ymax=upper, colour= NA, fill=stim), alpha=0.2) +
  
  scale_colour_manual(values=c("#D95F02","#7570B3"), name = "Stim-Type:", breaks=c("CSp","CSm"),
                      labels=c("CS+", "CS-")) +
  scale_fill_manual(values=c("#D95F02","#7570B3"), name = "Stim-Type:", breaks=c("CSp","CSm"),
                    labels=c("CS+", "CS-")) +
  xlab("Trial") +
  ylab(name_y_lab) + 
  scale_x_continuous(breaks=seq(1,12,1)) +
  scale_y_continuous(breaks=seq(0,y_limit,y_break), expand=c(0,0)) +
  coord_cartesian(ylim = c(0,y_limit)) + 
  
  ggtitle("Full sample") +
  
  theme(plot.title = element_blank(), plot.subtitle = element_blank(),
        axis.text.x = element_text(size=13,  color="black"),
        axis.text.y = element_text(size=12, color="black"), 
        axis.title.y = element_text(size=12, margin=margin(0,10,0,0)),
        legend.title = element_text(size=12),
        legend.text = element_text(size=12),
        legend.key = element_blank(),
        axis.line.x = element_line(color="black"),
        axis.line.y = element_line(color="black"),
        axis.ticks.x=element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) 

plot(SCR_logrc)

}
}

```

## Fear Potentiated Startle

``` {r include = FALSE}

load("fps_FPP_forR.RData")

# Exclude outliers: participants with less than 8/12 or 4/6 responses to the US 
fps_FPP_forR <- fps_FPP_forR[!((fps_FPP_forR$id == '8') | (fps_FPP_forR$id == '14') | (fps_FPP_forR$id == '22') | (fps_FPP_forR$id == '37') | (fps_FPP_forR$id == '57')),]
#Note: 024 shows response to 5 USs, but not a single response to any CS
                   
```


``` {r echo = FALSE}

phase <- c("acq","ext","ren")
reinf <- c("all","100","050")

for (i in phase){

  cat(paste0('Experimental phase: ', i, '\n'))
  
  for (k in reinf){
    
    cat(paste0('Reinforcement group: ', k, '\n'))

# create data subset
if (k == "all"){
dataSubset <- fps_FPP_forR[which(fps_FPP_forR$phase == i),]
} else {
dataSubset <- fps_FPP_forR[which(fps_FPP_forR$phase == i & fps_FPP_forR$reinf_rate == k),]
}

# Define n for SE
n <- length(unique(dataSubset$id))
cat(paste('Sample size: n = ', n, '\n'))

agg.fps <- with(dataSubset, aggregate(Tscore, by=list(trial=trial, stim=stim, phase=phase), FUN=mean, na.rm=T))
agg.fps$se <- with(dataSubset, aggregate(Tscore, by=list(trial=trial, stim=stim), FUN=se))[ ,3]

# Timline for x-axis
if (i == "ren"){ 
agg.fps$x_axis <- c(rep(c(1:6),2))
} else {
agg.fps$x_axis <- c(rep(c(1:12),2))
}

# Order corresponding to timeline
agg.fps <- agg.fps[order(agg.fps$trial),]

# Add confidence interval
agg.fps$lower <- agg.fps$x - 1.96*agg.fps$se
agg.fps$upper <- agg.fps$x + 1.96*agg.fps$se

name_y_lab <- "Startle (T-score)" 
y_low_limit <- round(min(agg.fps$lower))
y_upp_limit <- round(max(agg.fps$upper))
y_break <- 10

# Plot
theme_set(theme_bw())
fps <- ggplot(agg.fps, aes(x=x_axis, y=x, colour=stim, group=stim))+
  geom_point(aes(group=stim), size=2) +
  geom_line(aes(group=stim), size=1.2) +
  geom_ribbon(aes(ymin=lower, ymax=upper, colour= NA, fill=stim), alpha=0.2) +
  
  scale_colour_manual(values=c("#D95F02","#7570B3"), name = "Stim-Type:", breaks=c("CSp","CSm"),
                      labels=c("CS+", "CS-")) +
  scale_fill_manual(values=c("#D95F02","#7570B3"), name = "Stim-Type:", breaks=c("CSp","CSm"),
                    labels=c("CS+", "CS-")) +
  xlab("Trial") +
  ylab(name_y_lab) + 
  scale_x_continuous(breaks=seq(1,12,1)) +
  scale_y_continuous(breaks=seq(y_low_limit,y_upp_limit,y_break), expand=c(0,0)) +
  coord_cartesian(ylim = c(y_low_limit,y_upp_limit)) + 
  
  ggtitle("Full sample") +
  
  theme(plot.title = element_blank(), plot.subtitle = element_blank(),
        axis.text.x = element_text(size=13,  color="black"),
        axis.text.y = element_text(size=12, color="black"), 
        axis.title.y = element_text(size=12, margin=margin(0,10,0,0)),
        legend.title = element_text(size=12),
        legend.text = element_text(size=12),
        legend.key = element_blank(),
        axis.line.x = element_line(color="black"),
        axis.line.y = element_line(color="black"),
        axis.ticks.x=element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) 

plot(fps)

}
}

```

## Fear Ratings

``` {r include = FALSE}

load("rating_FPP_forR.RData")

#exclude renewal for ID 20, 21, 22, they didn't complete it
rating_FPP_forR<-rating_FPP_forR[!((rating_FPP_forR$id == 20) | (rating_FPP_forR$id == 21) | (rating_FPP_forR$id == 22)),]
   
```


``` {r echo = FALSE}
                
phase <- c("acq","ext","ren")
reinf <- c("all","100","050")

for (i in phase){

  cat(paste0('Experimental Phase: ', i, '\n'))
  
  for (k in reinf){
    
    cat(paste0('Reinforcement group: ', k, '\n'))

# create data subset
if (k == "all"){
dataSubset <- rating_FPP_forR[which(rating_FPP_forR$phase == i),]
} else {
dataSubset <- rating_FPP_forR[which(rating_FPP_forR$phase == i & rating_FPP_forR$reinf_rate == k),]
}

# Define n for SE
n <- length(unique(dataSubset$id)); 
cat(paste('Sample size: n = ', n, '\n'))

# mean of CS+ and CS- for each trial
agg.rate <- with(dataSubset, aggregate(Rating, by=list(trial=trial, stim=stim, phase=phase), FUN=mean, na.rm=T))
agg.rate$se <- with(dataSubset, aggregate(Rating, by=list(trial=trial, stim=stim, phase=phase), FUN=se))[ ,4] 

# Timline for x-axis
if (i == "ren"){ 
agg.rate$x_axis <- c(rep(c(1:6),2))
} else {
agg.rate$x_axis <- c(rep(c(1:12),2))
}

# Order corresponding to timeline
agg.rate <- agg.rate[order(agg.rate$trial),]

# Add confidence interval
agg.rate$lower <- agg.rate$x - 1.96*agg.rate$se
agg.rate$upper <- agg.rate$x + 1.96*agg.rate$se


# Plot first try
theme_set(theme_bw())
rating <- ggplot(agg.rate, aes(x=x_axis, y=x, colour=stim, group=stim))+
  geom_point(aes(group=stim), size=2) +
  geom_line(aes(group=stim), size=1.2) +
  geom_ribbon(aes(ymin=lower, ymax=upper, colour= stim, fill=stim), alpha=0.2) +
  
  scale_colour_manual(values=c("#D95F02","#7570B3"), name = "Stim-Type:", breaks=c("CSp","CSm"),
                      labels=c("CS+", "CS-")) +
  scale_fill_manual(values=c("#D95F02","#7570B3"), name = "Stim-Type:", breaks=c("CSp","CSm"),
                    labels=c("CS+", "CS-")) +
  xlab("Trial") +
  ylab("VAS Rating (0 - 100)") + 
  scale_x_continuous(breaks=c(seq(1,12,1),seq(13,24,1))) +
  scale_y_continuous(breaks=seq(0,100,5), expand=c(0,0)) +
  coord_cartesian(ylim = c(0,100)) +
  ggtitle("Full sample") +

  theme(plot.title = element_blank(), plot.subtitle = element_blank(),
    axis.text.x = element_text(size=13,  color="black"),
    axis.text.y = element_text(size=12, color="black"), 
    axis.title.y = element_text(size=12, margin=margin(0,10,0,0)),
    legend.title = element_text(size=12),
    legend.text = element_text(size=12),
    legend.key = element_blank(),
    axis.line.x = element_line(color="black"),
    axis.line.y = element_line(color="black"),
    axis.ticks.x=element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()) 

  plot(rating)
}
}

```